services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    ports:
     - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/9092'"]
      interval: 5s
      timeout: 5s
      retries: 12

  weather-producer:
    build: ./weather-producer
    depends_on:
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  weather-consumer:
    build: ./weather-consumer
    depends_on:
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
